# Persistent Volume Claim
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
     name: hr-sql-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: hr-sql-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi